language: java
jdk:
- oraclejdk8

notifications:
  email:
    on_success: change
    on_failure: change

cache:
  directories:
  - .autoconf
  - $HOME/.m2

install: true
before_script:
  - echo "MAVEN_OPTS='-Xmx2g -XX:MaxPermSize=512m'" >> ~/.mavenrc
script: cd data-prep && mvn clean verify -DskipTests=true
